# install layout information, following what qmake -query provides
get_filename_component(QT6_INSTALL_PREFIX
    ${CMAKE_CURRENT_LIST_DIR}/../../../ ABSOLUTE)
set(QT6_INSTALL_ARCHDATA "share/qt6")
set(QT6_INSTALL_BINS "bin")
set(QT6_INSTALL_CONFIGURATION "etc/xdg")
set(QT6_INSTALL_DATA "share/qt6")
set(QT6_INSTALL_DOCS "share/qt6/doc")
set(QT6_INSTALL_EXAMPLES "examples")
set(QT6_INSTALL_HEADERS "include/qt6")
set(QT6_INSTALL_LIBS "lib")
set(QT6_INSTALL_LIBEXECS "share/qt6/bin")
set(QT6_INSTALL_PLUGINS "share/qt6/plugins")
set(QT6_INSTALL_QML "share/qt6/qml")
set(QT6_INSTALL_TESTS "tests")
set(QT6_INSTALL_TRANSLATIONS "share/qt6/translations")
