/* This file was generated by syncqt. */
#ifndef QT_QTXML_VERSION_H
#define QT_QTXML_VERSION_H

#define QTXML_VERSION_STR "6.5.1"

#define QTXML_VERSION 0x060501

#endif // QT_QTXML_VERSION_H
