get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../" ABSOLUTE)
SET(OpenBLAS_VERSION "0.3.13")
SET(OpenBLAS_INCLUDE_DIRS ${PACKAGE_PREFIX_DIR}/include/OpenBLAS)
SET(OpenBLAS_LIBRARIES ${PACKAGE_PREFIX_DIR}/lib/libopenblas.dll.a)
